package Interface;
import javax.swing.JOptionPane;

import DAO.*;
import Modelo.*;

/**
 *
 * @author cambraia
 */
public class TelaCandidato extends javax.swing.JFrame {
	private CandidatoDAO cDAO=null;
	private PartidoDAO pDAO=null;
	private CentralBotão TelaSuperior=null;
    /**
     * Creates new form TelaCandidato
     */
	
	public TelaCandidato(CentralBotão TelaSuperior,CandidatoDAO cDAO,PartidoDAO pDAO) {
        initComponents();
        ConfirmarCandidato.setEnabled(false);
        this.cDAO=cDAO;
        this.pDAO=pDAO;
        this.TelaSuperior=TelaSuperior;
        CampoNumCandidato.setColumns(5);
    }
	public TelaCandidato() {
        initComponents();
        ConfirmarCandidato.setEnabled(false);
    }

    private boolean VerificaCampo(){
     	Documentos doc=new Documentos();
     	//Verifica se foi digitado algo no campo nome
        if (CampoNomeCandidato.getText().length() > 0) {
        	//Verifica se o Numero Candidato tem 5 caracteres
            if (CampoNumCandidato.getText().length() == 5) {
            	//Verifica se tem apenas Numeros em Campo Candidato
            	try {
            		Integer.parseInt(CampoNumCandidato.getText());
				} catch (Exception e) {
					ConfirmarCandidato.setEnabled(false);
					return false;
				}
            	//Verifica se Cpf tem a Quantidade Certa de caracteres
                if (CampoCPFC.getText().length() == 11 || CampoCPFC.getText().length() == 14) {//Verifica CPF
                	//Verifica se o Cpf Digitado é valido
                	if(doc.validaCpf(CampoCPFC.getText())) {
                		//Verifica se digitou algo no campo partido
                		if (CampoPartidoF.getText().length()>0) {
                			//Tem que verificar se o Partido Existe Começa procurando por Nome
                			Partido part=null;
                			part=pDAO.ObjectNome(CampoPartidoF.getText());
                			if(part==null) {
                				//Se não achou por nome ve se Digitou um numero no campo
                				try {
									Integer.parseInt(CampoPartidoF.getText());
								} catch (Exception e) {
									ConfirmarCandidato.setEnabled(false);
									return false;
								}
                				//Procura o Partido pelo numero
                				part=pDAO.ObjectNumero(Integer.parseInt(CampoPartidoF.getText()));
                				if(part==null) {
                					ConfirmarCandidato.setEnabled(false);
                					return false;
                				}
                			}
	                        ConfirmarCandidato.setEnabled(true);
	                        return true;
	                    }
                	}
                }
            }
        }
        ConfirmarCandidato.setEnabled(false);
        return false;
      }
   
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LabelNomeCandidato = new javax.swing.JLabel();
        CampoNomeCandidato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumCandidato = new javax.swing.JLabel();
        CampoNumCandidato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelCPFC = new javax.swing.JLabel();
        CampoCPFC = new javax.swing.JTextField();
        CampoPartidoF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LabelPartidoF = new javax.swing.JLabel();
        ConfirmarCandidato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        LabelNomeCandidato.setText("Nome do candidato");
        jLabelNumCandidato.setText("Numero do candidato");
        jLabelCPFC.setText("CPF do candidato"); 
        LabelPartidoF.setText("Partido Filiado");

        ConfirmarCandidato.setText("Criar Candidato");
        ConfirmarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarCandidatoActionPerformed(evt);
            }
        });
        CampoNomeCandidato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            	VerificaCampo(evt);
            }
        });
        CampoNumCandidato.addKeyListener(new java.awt.event.KeyAdapter() {
        	public void keyPressed(java.awt.event.KeyEvent evt) {
        		if (CampoNumCandidato.getText().length() >= 5) {
        			CampoNumCandidato.setText(CampoNumCandidato.getText().substring(0,4));
        		}
        	}
        	public void keyReleased(java.awt.event.KeyEvent evt) {
            	VerificaCampo(evt);
            }
        });
        CampoCPFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            	VerificaCampo(evt);
            }
        });
        CampoPartidoF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            	VerificaCampo(evt);
            } 
        });
        this.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            	VerificaCampo(evt);
            }
        });
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CampoNomeCandidato)
            .addComponent(CampoNumCandidato)
            .addComponent(CampoCPFC)
            .addComponent(CampoPartidoF)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelCPFC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(LabelNomeCandidato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNumCandidato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LabelPartidoF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(ConfirmarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNomeCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampoNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNumCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoNumCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCPFC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoCPFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelPartidoF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoPartidoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void CampoNomeCandidatoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
    	// TODO add your handling code here:
    }                                                  

    private void CampoNumCandidatoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void ConfirmarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {           
			Partido part=null;
			part=pDAO.ObjectNome(CampoPartidoF.getText());//Procura Partido pelo Nome
			if(part==null) {
				//Se não achou por nome  Procura o Partido pelo numero
				part=pDAO.ObjectNumero(Integer.parseInt(CampoPartidoF.getText()));
				if(part==null) {
					JOptionPane.showMessageDialog(null, "Partido Invalido");//Provavelmente nunca passará por aqui
					return;
				}
			}
			boolean criado=false;
    	try {
    		criado=cDAO.CriarCandidato(CampoNomeCandidato.getText(), CampoNumCandidato.getText(), CampoCPFC.getText(),part);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Erro ao cadastrar");
		}
    	if(criado==true) {
    		Documentos doc=new Documentos(CampoCPFC.getText());
    		JOptionPane.showMessageDialog(null, "Cadastrado com sucesso \n "+"Nome:"+CampoNomeCandidato.getText()+"\nNumero:"+CampoNumCandidato.getText()+"\nCPF:"+doc.toStringPonto()+"\nNome Partido:"+part.getNome()+"\nNumero Partido:"+part.getNumero());
    		TelaSuperior.setVisible(true);
    		this.dispose();
    	}
    }                                                  

    private void VerificaCampo(java.awt.event.KeyEvent evt) { 
    	//ERRO Quero primeiro adicionar o Numero ao campo e depois Chamar o evento AJUDA
    	VerificaCampo();
    }    
                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField CampoCPFC;
    private javax.swing.JTextField CampoNomeCandidato;
    private javax.swing.JTextField CampoNumCandidato;
    private javax.swing.JTextField CampoPartidoF;
    private javax.swing.JButton ConfirmarCandidato;
    private javax.swing.JLabel LabelNomeCandidato;
    private javax.swing.JLabel LabelPartidoF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCPFC;
    private javax.swing.JLabel jLabelNumCandidato;
    // End of variables declaration                   
}
