/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;
import CENTRAL.Central;
/**
 *
 * @author lucas
 */
public class TelaCentral extends javax.swing.JFrame {
    private Central instancia=null;
    /**
     * Creates new form NewJFrame
     */
    public TelaCentral() {
        initComponents();
    }
    public TelaCentral(Central central) {
        this.instancia=central;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        EleitorButaoCriar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EleitorCampoNome = new javax.swing.JTextField();
        EleitorLabelNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EleitorCampoTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EleitorCampoCPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EleitorCampoUrna = new javax.swing.JTextField();
        EleitorLabelTitulo = new javax.swing.JLabel();
        EleitorLabelCPF = new javax.swing.JLabel();
        EleitorLabelUrna = new javax.swing.JLabel();
        Eleitor = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        CandidatoButaoCriar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CandidatoCampoNome = new javax.swing.JTextField();
        CandidatoLabelNome1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CandidatoCampoNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CandidatoCampoCPF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CandidatoCampoPartido = new javax.swing.JTextField();
        CandidatoLabelNumero = new javax.swing.JLabel();
        CandidatoLabelCPF = new javax.swing.JLabel();
        CandidatoLabelPartido = new javax.swing.JLabel();
        Candidato = new javax.swing.JLabel();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        PartidoButaoCriar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        PartidoCampoNome = new javax.swing.JTextField();
        PartidoLabelNome = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PartidoCampoNumero = new javax.swing.JTextField();
        PartidoLabelNumero = new javax.swing.JLabel();
        Partido = new javax.swing.JLabel();

        jLabel4.setText("jLabel1");

        jTextField3.setText("jTextField1");

        jLabel9.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLayeredPane5.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tabela", jLayeredPane5);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList3);

        jLayeredPane6.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 661, Short.MAX_VALUE))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Lista", jLayeredPane6);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Texto", jLayeredPane2);

        jTabbedPane1.addTab("Resultado", jTabbedPane2);

        EleitorButaoCriar.setText("Criar");
        EleitorButaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleitorButaoCriarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Eleitor");

        EleitorCampoNome.setText("Digite...");
        EleitorCampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleitorCampoNomeActionPerformed(evt);
            }
        });

        EleitorLabelNome.setText("Erro");

        jLabel3.setText("Titulo de Eleito");

        EleitorCampoTitulo.setText("Digite...");
        EleitorCampoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleitorCampoTituloActionPerformed(evt);
            }
        });

        jLabel5.setText("CPF - Cadastro de Pessoa Física");

        EleitorCampoCPF.setText("Digite...");
        EleitorCampoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleitorCampoCPFActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero da Urna de Votacao");

        EleitorCampoUrna.setText("Digite...");

        EleitorLabelTitulo.setText("Erro");

        EleitorLabelCPF.setText("Erro");

        EleitorLabelUrna.setText("Erro");

        Eleitor.setText("Dados Cadastrados");

        jLayeredPane3.setLayer(EleitorButaoCriar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EleitorCampoNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EleitorLabelNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EleitorCampoTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EleitorCampoCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EleitorCampoUrna, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EleitorLabelTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EleitorLabelCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(EleitorLabelUrna, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(Eleitor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EleitorCampoNome)
                            .addComponent(jLabel3)
                            .addComponent(EleitorCampoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(EleitorCampoUrna, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(EleitorCampoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(Eleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EleitorLabelNome)
                            .addComponent(EleitorLabelTitulo)
                            .addComponent(EleitorLabelCPF)
                            .addComponent(EleitorLabelUrna))))
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EleitorButaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(EleitorButaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(EleitorCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EleitorCampoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EleitorCampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EleitorCampoUrna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(EleitorLabelNome)
                        .addGap(46, 46, 46)
                        .addComponent(EleitorLabelTitulo)
                        .addGap(46, 46, 46)
                        .addComponent(EleitorLabelCPF)
                        .addGap(46, 46, 46)
                        .addComponent(EleitorLabelUrna)))
                .addGap(18, 18, 18)
                .addComponent(Eleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eleitor", jLayeredPane3);

        CandidatoButaoCriar1.setText("Criar");
        CandidatoButaoCriar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatoButaoCriar1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome candidato");

        CandidatoCampoNome.setText("Digite...");

        CandidatoLabelNome1.setText("Erro");

        jLabel7.setText("Numero");

        CandidatoCampoNumero.setText("Digite...");
        CandidatoCampoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatoCampoNumeroActionPerformed(evt);
            }
        });

        jLabel8.setText("CPF - Cadastro de Pessoa Física");

        CandidatoCampoCPF.setText("Digite...");
        CandidatoCampoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatoCampoCPFActionPerformed(evt);
            }
        });

        jLabel10.setText("Partido");

        CandidatoCampoPartido.setText("Digite...");

        CandidatoLabelNumero.setText("Erro");

        CandidatoLabelCPF.setText("Erro");

        CandidatoLabelPartido.setText("Erro");

        Candidato.setText("Dados Cadastrados");

        jLayeredPane7.setLayer(CandidatoButaoCriar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CandidatoCampoNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CandidatoLabelNome1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CandidatoCampoNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CandidatoCampoCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CandidatoCampoPartido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CandidatoLabelNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CandidatoLabelCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CandidatoLabelPartido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(Candidato, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CandidatoCampoNome)
                            .addComponent(jLabel7)
                            .addComponent(CandidatoCampoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(CandidatoCampoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(CandidatoCampoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(Candidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CandidatoLabelNome1)
                            .addComponent(CandidatoLabelNumero)
                            .addComponent(CandidatoLabelCPF)
                            .addComponent(CandidatoLabelPartido))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane7Layout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(CandidatoButaoCriar1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addComponent(CandidatoButaoCriar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addComponent(CandidatoCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CandidatoCampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CandidatoCampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CandidatoCampoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addComponent(CandidatoLabelNome1)
                        .addGap(46, 46, 46)
                        .addComponent(CandidatoLabelNumero)
                        .addGap(46, 46, 46)
                        .addComponent(CandidatoLabelCPF)
                        .addGap(46, 46, 46)
                        .addComponent(CandidatoLabelPartido)))
                .addGap(18, 18, 18)
                .addComponent(Candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Candidato", jLayeredPane7);

        PartidoButaoCriar.setText("Criar");
        PartidoButaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoButaoCriarActionPerformed(evt);
            }
        });

        jLabel13.setText("Nome Partido");

        PartidoCampoNome.setText("Digite...");

        PartidoLabelNome.setText("Erro");

        jLabel14.setText("Numero Partido");

        PartidoCampoNumero.setText("Digite...");
        PartidoCampoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoCampoNumeroActionPerformed(evt);
            }
        });

        PartidoLabelNumero.setText("Erro");

        Partido.setText("Dados Cadastrados");

        jLayeredPane8.setLayer(PartidoButaoCriar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(PartidoCampoNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(PartidoLabelNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(PartidoCampoNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(PartidoLabelNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(Partido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jLayeredPane8Layout.createSequentialGroup()
                        .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PartidoCampoNome)
                            .addComponent(jLabel14)
                            .addComponent(PartidoCampoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(Partido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PartidoLabelNome)
                            .addComponent(PartidoLabelNumero))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane8Layout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(PartidoButaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addComponent(PartidoButaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane8Layout.createSequentialGroup()
                        .addComponent(PartidoCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PartidoCampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane8Layout.createSequentialGroup()
                        .addComponent(PartidoLabelNome)
                        .addGap(46, 46, 46)
                        .addComponent(PartidoLabelNumero)))
                .addGap(18, 18, 18)
                .addComponent(Partido, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Partido", jLayeredPane8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CandidatoCampoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatoCampoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CandidatoCampoCPFActionPerformed

    private void CandidatoCampoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatoCampoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CandidatoCampoNumeroActionPerformed

    private void EleitorCampoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleitorCampoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EleitorCampoCPFActionPerformed

    private void EleitorCampoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleitorCampoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EleitorCampoTituloActionPerformed

    private void PartidoCampoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoCampoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartidoCampoNumeroActionPerformed

    private void EleitorButaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleitorButaoCriarActionPerformed
        //Pegando da tela e salvando em variaveis
        boolean validacao=false;
        String Path=null;
        String CampoNome=EleitorCampoNome.getText();
        String CampoTitulo=EleitorCampoTitulo.getText();
        String CampoCPF=EleitorCampoCPF.getText();
        String CampoUrna=EleitorCampoUrna.getText();
        validacao=instancia.CriarEleitor(Path, CampoNome, CampoTitulo, CampoCPF, CampoUrna);
        if(validacao){
            String DadosCadastrados="";
            DadosCadastrados="Nome: "+CampoNome+
                            "\nTitulo: "+CampoTitulo+
                            "\nCpf: "+CampoCPF+
                            "\nUrna: "+CamposUrna;
            Eleitor.setText(DadosCadastrados);
        }
    }//GEN-LAST:event_EleitorButaoCriarActionPerformed

    private void EleitorCampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleitorCampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EleitorCampoNomeActionPerformed

    private void PartidoButaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoButaoCriarActionPerformed
        boolean validacao=false;
        String CampoNumeroPartido=PartidoCampoNumero.getText();
        String CampoNomePartido=PartidoCampoNome.getText();
        validacao=instancia.CadastrarPartido(CampoNumeroPartido, CampoNomePartido);
        if(validacao){
            String DadosPartido="Numero: "+CampoNumeroPartido+
                                "\nNome: "+CampoNomePartido;
            
            Partido.setText(DadosPartido);
        }
        
    }//GEN-LAST:event_PartidoButaoCriarActionPerformed

    private void CandidatoButaoCriar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatoButaoCriar1ActionPerformed
        boolean validacao=false;
        String CampoNomeCandidato=CandidatoCampoNome.getText();
        String CampoNumeroCandidato=CandidatoCampoNumero.getText();
        String CampoCPF=CandidatoCampoCPF.getText();
        String CampoPartido=CandidatoCampoPartido.getText();
        validacao = instancia.CadastrarCandidato(CampoPartido, CampoNomeCandidato, CampoNumeroCandidato, CampoCPF)
        if(validacao){
            String DadosCandidato="Nome: "+CampoNomeCandidato+
                                  "\nNumero: "+CampoNumeroCandidato+
                                  "\nCPF: "+CampoCPF+
                                  "\nPartido: "+CampoPartido;
            Candidato.setText(DadosCandidato);
        }
    }//GEN-LAST:event_CandidatoButaoCriar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Candidato;
    private javax.swing.JButton CandidatoButaoCriar1;
    private javax.swing.JTextField CandidatoCampoCPF;
    private javax.swing.JTextField CandidatoCampoNome;
    private javax.swing.JTextField CandidatoCampoNumero;
    private javax.swing.JTextField CandidatoCampoPartido;
    private javax.swing.JLabel CandidatoLabelCPF;
    private javax.swing.JLabel CandidatoLabelNome1;
    private javax.swing.JLabel CandidatoLabelNumero;
    private javax.swing.JLabel CandidatoLabelPartido;
    private javax.swing.JLabel Eleitor;
    private javax.swing.JButton EleitorButaoCriar;
    private javax.swing.JTextField EleitorCampoCPF;
    private javax.swing.JTextField EleitorCampoNome;
    private javax.swing.JTextField EleitorCampoTitulo;
    private javax.swing.JTextField EleitorCampoUrna;
    private javax.swing.JLabel EleitorLabelCPF;
    private javax.swing.JLabel EleitorLabelNome;
    private javax.swing.JLabel EleitorLabelTitulo;
    private javax.swing.JLabel EleitorLabelUrna;
    private javax.swing.JLabel Partido;
    private javax.swing.JButton PartidoButaoCriar;
    private javax.swing.JTextField PartidoCampoNome;
    private javax.swing.JTextField PartidoCampoNumero;
    private javax.swing.JLabel PartidoLabelNome;
    private javax.swing.JLabel PartidoLabelNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
